---
- name: Download shell scripts locally
  hosts: Miners
  tasks:
    - name: run cmd
      shell: if cd ~/blocrypt; then git pull; else git clone https://github.com/CamJohnson26/blocrypt blocrypt; fi
