---
- name: Send GPU Info to cameronrossjohnson@gmail.com
  hosts: Miners
  tasks:
    - name: run cmd
      shell: nvidia-smi
      register: gpuState
    - name: run cmd
      shell: nvidia-smi -L
      register: gpuList
    - name: run cmd
      shell: nvidia-smi -q | grep -E 'GPU UUID|Bus Id'
      register: gpuInfoBusToGuid
    - name: run cmd
      shell: lspci -v | grep -E 'Subsystem|VGA compatible'
      register: gpuInfoBusToBrand
    - mail:
        host: aspmx.l.google.com
        port: 25
        from: awx@25.13.82.123.com
        to: Cameron Johnson <cameronrossjohnson@gmail.com>
        subject: Miner GPU Info
        body: "GPU Information. \n\nGPU State\n {{\"%s\" | format(gpuState.stdout)}} \n\nGPU List\n{{\"%s\" | format(gpuList.stdout) }} \n\nGPU Bus to GUID\n {{\"%s\" | format(gpuInfoBusToGuid.stdout) }} \n\nGPU Bus to Brand\n {{\"%s\" | format(gpuInfoBusToBrand.stdout) }}"
      delegate_to: localhost