---
- name: Send GPU Info to cameronrossjohnson@gmail.com
  hosts: Miners
  tasks:
    - name: run cmd
      shell: nvidia-smi
      register: gpuInfo
    - mail:
        host: aspmx.l.google.com
        port: 25
        to: Cameron Johnson <cameronrossjohnson@gmail.com>
        subject: Miner GPU Info
        body: "This is a test email. {{ \n\ngpuInfo }}"